--------------------------------------------------------
--  파일이 생성됨 - 월요일-5월-08-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence BOARD_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##GROUP7"."BOARD_SQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 201 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BUCKET_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##GROUP7"."BUCKET_SEQ"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 114 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COMMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##GROUP7"."COMMENT_SEQ"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 79 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COMMENT_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##GROUP7"."COMMENT_SQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 341 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence GROUP_BOARD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##GROUP7"."GROUP_BOARD_SEQ"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 37 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence GROUP_COMMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##GROUP7"."GROUP_COMMENT_SEQ"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 27 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence LIKE_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##GROUP7"."LIKE_SQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 241 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REGISTER_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##GROUP7"."REGISTER_SQ"  MINVALUE 1 MAXVALUE 50000 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  CYCLE ;
--------------------------------------------------------
--  DDL for Sequence REPORT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##GROUP7"."REPORT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 141 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USER_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##GROUP7"."USER_SQ"  MINVALUE 1 MAXVALUE 50000 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  CYCLE ;
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "C##GROUP7"."BOARD" 
   (	"NO" NUMBER, 
	"SUBJECT" VARCHAR2(300 BYTE), 
	"CONTENT" CLOB, 
	"USERID" VARCHAR2(20 BYTE), 
	"USERNAME" VARCHAR2(20 BYTE), 
	"HIT" NUMBER, 
	"WRITEDATE" DATE, 
	"IP" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table BUCKET_COMMENT
--------------------------------------------------------

  CREATE TABLE "C##GROUP7"."BUCKET_COMMENT" 
   (	"COMMENT_NO" VARCHAR2(255 BYTE), 
	"BUCKET_NO" NUMBER, 
	"USERID" VARCHAR2(20 BYTE), 
	"COMMENT_CONTENT" VARCHAR2(200 BYTE), 
	"COMMENT_WRITEDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BUCKET_LIKE
--------------------------------------------------------

  CREATE TABLE "C##GROUP7"."BUCKET_LIKE" 
   (	"USERID" VARCHAR2(20 BYTE), 
	"BUCKET_NO" NUMBER, 
	"LIKE_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BUCKET_REF
--------------------------------------------------------

  CREATE TABLE "C##GROUP7"."BUCKET_REF" 
   (	"BUCKET_NO" NUMBER, 
	"USERID" VARCHAR2(20 BYTE), 
	"TITLE" VARCHAR2(50 BYTE), 
	"CONTENT" CLOB, 
	"BUCKET_WRITEDATE" DATE DEFAULT sysdate, 
	"PROGRESS_STATUS" CHAR(1 BYTE) DEFAULT 0, 
	"LIKE_COUNT" NUMBER DEFAULT 0, 
	"CATEGORY" VARCHAR2(20 BYTE), 
	"ISGROUP" VARCHAR2(20 BYTE), 
	"PROGRESS" NUMBER(3,0) DEFAULT 0, 
	"ISVISIBLE" VARCHAR2(20 BYTE) DEFAULT 1, 
	"CAPACITY" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table BUCKET_REPORT
--------------------------------------------------------

  CREATE TABLE "C##GROUP7"."BUCKET_REPORT" 
   (	"BUCKET_NO" NUMBER, 
	"TITLE" VARCHAR2(50 BYTE), 
	"CONTENT" CLOB, 
	"REPORT_NO" NUMBER, 
	"REPORT_TITLE" VARCHAR2(200 BYTE), 
	"REPORT_CONTENT" VARCHAR2(500 BYTE), 
	"REPORT_CATEGORY" NUMBER, 
	"REPORT_WRITEDATE" DATE DEFAULT sysdate, 
	"REPORT_USERID" VARCHAR2(100 BYTE), 
	"REPORT_PROGRESS" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table COMMENT_BOARD
--------------------------------------------------------

  CREATE TABLE "C##GROUP7"."COMMENT_BOARD" 
   (	"C_NO" NUMBER, 
	"NO" NUMBER, 
	"COMENT" CLOB, 
	"USERID" VARCHAR2(50 BYTE), 
	"WRITEDATE" DATE, 
	"IP" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("COMENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table GROUP_BOARD_COMMENT
--------------------------------------------------------

  CREATE TABLE "C##GROUP7"."GROUP_BOARD_COMMENT" 
   (	"GROUP_COMMENT_NO" NUMBER, 
	"GROUP_NO" NUMBER, 
	"USERID" VARCHAR2(20 BYTE), 
	"GROUP_BOARD_NO" NUMBER, 
	"GROUP_COMMENT_CONTENT" VARCHAR2(200 BYTE), 
	"GROUP_COMMENT_WRITEDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GROUP_BUCKET_BOARD
--------------------------------------------------------

  CREATE TABLE "C##GROUP7"."GROUP_BUCKET_BOARD" 
   (	"GROUP_BOARD_NO" NUMBER, 
	"GROUP_NO" NUMBER, 
	"USERID" VARCHAR2(20 BYTE), 
	"GROUP_TITLE" VARCHAR2(50 BYTE), 
	"GROUP_CONTENT" CLOB, 
	"GROUP_WRITEDATE" DATE DEFAULT sysdate, 
	"ISNOTICE" CHAR(1 BYTE) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("GROUP_CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table GROUP_MEMBER_LIST
--------------------------------------------------------

  CREATE TABLE "C##GROUP7"."GROUP_MEMBER_LIST" 
   (	"USERID" VARCHAR2(20 BYTE), 
	"GROUP_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GROUP_QUEUE
--------------------------------------------------------

  CREATE TABLE "C##GROUP7"."GROUP_QUEUE" 
   (	"GROUP_NO" NUMBER, 
	"USERID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table IMAGEPATH
--------------------------------------------------------

  CREATE TABLE "C##GROUP7"."IMAGEPATH" 
   (	"BUCKET_NO" NUMBER, 
	"FILENAME" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROFILE
--------------------------------------------------------

  CREATE TABLE "C##GROUP7"."PROFILE" 
   (	"USERID" VARCHAR2(64 BYTE), 
	"STATUS_MESSAGE" VARCHAR2(100 BYTE), 
	"FILENAME" VARCHAR2(200 BYTE), 
	"PROFILE_VISIBLE" CHAR(1 BYTE) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERTABLE
--------------------------------------------------------

  CREATE TABLE "C##GROUP7"."USERTABLE" 
   (	"USERID" VARCHAR2(64 BYTE), 
	"USERPWD" VARCHAR2(128 BYTE), 
	"USERNAME" VARCHAR2(20 BYTE), 
	"TEL" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"USERNICK" VARCHAR2(40 BYTE), 
	"REGISTERDATE" DATE DEFAULT sysdate, 
	"PERMISSION" CHAR(1 BYTE) DEFAULT 0, 
	"NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into C##GROUP7.BOARD
SET DEFINE OFF;
Insert into C##GROUP7.BOARD (NO,SUBJECT,USERID,USERNAME,HIT,WRITEDATE,IP) values (187,'날이 점점 더워지네요','codnjs1003','뺘냐나',3,to_date('23/05/08','RR/MM/DD'),'0:0:0:0:0:0:0:1');
Insert into C##GROUP7.BOARD (NO,SUBJECT,USERID,USERNAME,HIT,WRITEDATE,IP) values (161,'초보 등린이 등산하기 좋은 산 추천해주세요 ㅎㅎㅎ','chaechae',null,7,to_date('23/05/07','RR/MM/DD'),'0:0:0:0:0:0:0:1');
Insert into C##GROUP7.BOARD (NO,SUBJECT,USERID,USERNAME,HIT,WRITEDATE,IP) values (188,'요즘 영화 추천좀 해주세요!!','tjdwns123',null,2,to_date('23/05/08','RR/MM/DD'),'0:0:0:0:0:0:0:1');
Insert into C##GROUP7.BOARD (NO,SUBJECT,USERID,USERNAME,HIT,WRITEDATE,IP) values (184,'별 보기 좋은 곳 있나요?','chaechae',null,5,to_date('23/05/08','RR/MM/DD'),'0:0:0:0:0:0:0:1');
Insert into C##GROUP7.BOARD (NO,SUBJECT,USERID,USERNAME,HIT,WRITEDATE,IP) values (190,'서울에서 같이 고기드실분?','test1234',null,0,to_date('23/05/08','RR/MM/DD'),'0:0:0:0:0:0:0:1');
Insert into C##GROUP7.BOARD (NO,SUBJECT,USERID,USERNAME,HIT,WRITEDATE,IP) values (189,'벌써 모기가;;','tjdwns123',null,3,to_date('23/05/08','RR/MM/DD'),'0:0:0:0:0:0:0:1');
Insert into C##GROUP7.BOARD (NO,SUBJECT,USERID,USERNAME,HIT,WRITEDATE,IP) values (191,'같이 영화보실분!!!!!!!!!','test1234',null,0,to_date('23/05/08','RR/MM/DD'),'0:0:0:0:0:0:0:1');
Insert into C##GROUP7.BOARD (NO,SUBJECT,USERID,USERNAME,HIT,WRITEDATE,IP) values (181,'서울 삼겹살 맛집 추천점','test1234',null,5,to_date('23/05/08','RR/MM/DD'),'0:0:0:0:0:0:0:1');
REM INSERTING into C##GROUP7.BUCKET_COMMENT
SET DEFINE OFF;
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('28',61,'cwcwcw123','헐 고양이 너무 귀엽다',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('29',61,'cwcwcw123','나두 키우고싶어요',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('76',110,'lyctg4620','저두 외국인 친구..',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('31',73,'chaechae','저요저요',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('32',74,'lyctg4620','가오갤 이번꺼 완전 재밌어요',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('33',74,'test1234','같이가요!',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('34',73,'test1234','저도 참여할게요!',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('35',71,'test1234','초보자도 가능한가요?',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('36',67,'test1234','저도 직관해보고싶네요!',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('37',65,'test1234','좋아요!',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('38',64,'test1234','저는 100점 넘기부터..!',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('39',77,'tjdwns123','파이팅!',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('40',76,'tjdwns123','저도 탁구 좋아하는데 같이 파이팅해요!',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('77',110,'codnjs1003','헉 대단해요
',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('42',71,'lyctg4620','네 저도 초보자에요 그룹 참여 요청 해주세요!',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('43',74,'tjdwns123','요번꺼 강추입니다!',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('44',79,'tjdwns123','혹시 초보도 가능한가요..?',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('45',78,'tjdwns123','저요!!!',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('46',68,'tjdwns123',':)',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('47',69,'tjdwns123','오호! 파이팅입니다~~',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('48',70,'tjdwns123','서핑 재밌어요 ㅎㅎ',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('49',67,'tjdwns123','저도요!!',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('50',71,'tjdwns123','파이팅!',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('51',73,'tjdwns123','디저트 너무 좋아요..!',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('52',80,'tjdwns123','헉 참여할게요!',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('53',76,'codnjs1003','와 입상하기 넘 머시써여!!',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('54',80,'codnjs1003','한우 오마카세 너무 좋아요',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('55',78,'codnjs1003','좋아요 같이해요!!',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('56',74,'codnjs1003','재밌나요?? 저도 보러갈래요',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('57',87,'tjdwns123','헉 파이팅이에요!!',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('58',89,'tjdwns123','같이가요~!',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('59',95,'tjdwns123','응원할게요!',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('60',95,'thdthd123',':)',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('78',111,'codnjs1003','스위스 너무 좋아요',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('62',92,'thdthd123','김장 파이팅입니다~',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('63',89,'thdthd123','저도 무서워서..',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('64',88,'thdthd123','우와 같이해봐요!',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('65',87,'thdthd123','우와!',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('66',80,'thdthd123','스시 좋습니다',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('67',79,'thdthd123','파이팅!',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('68',78,'thdthd123','저요!',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('69',77,'thdthd123','같이 운동해요!',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('70',76,'thdthd123','파이팅!',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('72',95,'thdthd123','파이팅!',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('73',89,'chaechae','헉 재밌겠다...',to_date('23/05/08','RR/MM/DD'));
Insert into C##GROUP7.BUCKET_COMMENT (COMMENT_NO,BUCKET_NO,USERID,COMMENT_CONTENT,COMMENT_WRITEDATE) values ('74',78,'lyctg4620','수영 좋아요!!',to_date('23/05/08','RR/MM/DD'));
REM INSERTING into C##GROUP7.BUCKET_LIKE
SET DEFINE OFF;
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('lyctg4620',61,161);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('cwcwcw123',61,162);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('test1234',66,163);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('chaechae',74,164);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('chaechae',73,165);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('test1234',76,166);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('thdthd123',109,220);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('test1234',74,168);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('test1234',70,172);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('test1234',73,170);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('test1234',71,171);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('test1234',69,173);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('test1234',68,174);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('test1234',67,175);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('test1234',65,176);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('test1234',64,177);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('tjdwns123',77,178);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('tjdwns123',76,179);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('thdthd123',110,221);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('lyctg4620',71,181);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('tjdwns123',79,182);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('tjdwns123',78,183);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('tjdwns123',68,184);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('tjdwns123',69,185);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('tjdwns123',70,186);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('tjdwns123',67,187);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('tjdwns123',71,188);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('tjdwns123',73,189);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('chaechae',110,222);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('codnjs1003',80,191);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('codnjs1003',78,192);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('codnjs1003',74,193);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('tjdwns123',88,194);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('tjdwns123',87,195);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('tjdwns123',91,196);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('tjdwns123',89,197);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('chaechae',53,198);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('tjdwns123',92,199);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('chaechae',113,223);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('tjdwns123',80,201);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('tjdwns123',95,202);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('chaechae',111,224);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('thdthd123',92,205);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('thdthd123',89,206);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('thdthd123',88,207);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('thdthd123',87,208);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('thdthd123',80,209);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('thdthd123',79,210);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('thdthd123',77,211);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('thdthd123',76,212);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('lyctg4620',108,225);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('thdthd123',95,214);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('chaechae',92,215);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('chaechae',80,217);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('lyctg4620',78,218);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('codnjs1003',111,230);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('lyctg4620',110,226);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('lyctg4620',112,228);
Insert into C##GROUP7.BUCKET_LIKE (USERID,BUCKET_NO,LIKE_NO) values ('codnjs1003',110,229);
REM INSERTING into C##GROUP7.BUCKET_REF
SET DEFINE OFF;
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (62,'lyctg4620','네이버 입사하기',to_date('23/05/08','RR/MM/DD'),'0',0,'accomplishment','0',0,'1',1);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (53,'chaechae','블랙핑크 콘서트 가기',to_date('23/05/06','RR/MM/DD'),'2',1,'fun','0',0,'1',1);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (59,'admin1234','test',to_date('23/05/07','RR/MM/DD'),'0',0,'travel','0',0,'1',1);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (60,'cwcwcw123','매일 강아지 산책 2번씩 나가기!',to_date('23/05/08','RR/MM/DD'),'0',0,'wealth','0',0,'1',1);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (99,'lyctg4620','손흥민 싸인 받기',to_date('23/05/08','RR/MM/DD'),'0',0,'challenge','0',0,'1',1);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (61,'lyctg4620','고양이 키우기',to_date('23/05/08','RR/MM/DD'),'0',2,'relationships','1',0,'1',10);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (56,'cwcwcw123','매주 일요일 등산하기',to_date('23/05/06','RR/MM/DD'),'0',0,'accomplishment','1',0,'1',10);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (63,'lyctg4620','제주도 여행가기',to_date('23/05/08','RR/MM/DD'),'0',0,'travel','1',0,'1',4);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (58,'admin1234','test',to_date('23/05/07','RR/MM/DD'),'0',0,'relationships','0',0,'0',1);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (64,'lyctg4620','볼링 200점 넘기',to_date('23/05/08','RR/MM/DD'),'0',1,'fun','1',0,'1',4);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (65,'cwcwcw123','자기전에 책 읽기',to_date('23/05/08','RR/MM/DD'),'1',1,'development','1',0,'1',5);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (66,'cwcwcw123','올여름 맛집탐방 가실분!',to_date('23/05/08','RR/MM/DD'),'0',1,'travel','1',0,'1',4);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (67,'lyctg4620','축구 직관하러가기',to_date('23/05/08','RR/MM/DD'),'0',2,'travel','1',0,'1',3);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (68,'test1234','에펠 탑 보러가기!!!!!!',to_date('23/05/08','RR/MM/DD'),'0',2,'travel','0',0,'1',1);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (69,'test1234','나만의 책 쓰기',to_date('23/05/08','RR/MM/DD'),'0',2,'challenge','0',0,'1',1);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (70,'test1234','서핑 배워보기@@@@',to_date('23/05/08','RR/MM/DD'),'0',2,'fun','1',0,'1',4);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (71,'lyctg4620','테니스 배우기',to_date('23/05/08','RR/MM/DD'),'0',3,'training','1',0,'1',2);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (73,'codnjs1003','디저트 맛집 탐방하기',to_date('23/05/08','RR/MM/DD'),'0',3,'eat','1',0,'1',4);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (74,'chaechae','가디언즈 오브 갤럭시 보러가실 분?',to_date('23/05/08','RR/MM/DD'),'0',3,'relationships','1',0,'1',5);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (76,'test1234','탁구 대회나가서 입상하기!!!',to_date('23/05/08','RR/MM/DD'),'0',3,'challenge','0',0,'1',1);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (77,'lyctg4620','퇴근후 헬스장가기',to_date('23/05/08','RR/MM/DD'),'0',2,'accomplishment','1',0,'1',2);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (78,'codnjs1003','저랑 수영 배우실 분!',to_date('23/05/08','RR/MM/DD'),'0',3,'training','1',0,'1',3);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (79,'codnjs1003','올 여름 뜨개질 가방 같이 만드실분!',to_date('23/05/08','RR/MM/DD'),'0',2,'fun','1',0,'1',5);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (80,'lyctg4620','한달에 2번 오마카세 투어하기',to_date('23/05/08','RR/MM/DD'),'0',4,'eat','1',0,'1',4);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (87,'codnjs1003','빨주노초파남보 염색 다 해볼껍니다!',to_date('23/05/08','RR/MM/DD'),'0',2,'challenge','0',0,'1',1);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (88,'tjdwns123','나만의 책상 만들어보기!',to_date('23/05/08','RR/MM/DD'),'0',2,'fun','1',0,'1',3);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (89,'codnjs1003','여름에 공포연극 보러 가실분..!',to_date('23/05/08','RR/MM/DD'),'0',2,'fun','1',0,'1',4);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (90,'codnjs1003','비즈팔찌 같이 만드실분',to_date('23/05/08','RR/MM/DD'),'2',0,'fun','1',0,'0',4);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (91,'tjdwns123','나만의 가방 만들기~~',to_date('23/05/08','RR/MM/DD'),'0',1,'fun','0',0,'0',1);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (92,'tjdwns123','김장해보기!!!',to_date('23/05/08','RR/MM/DD'),'0',3,'eat','0',0,'1',1);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (96,'chriso12345','캠핑가서 불멍하기',to_date('23/05/08','RR/MM/DD'),'0',0,'wealth','0',0,'1',1);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (95,'codnjs1003','하루한장 드로잉 연습하기',to_date('23/05/08','RR/MM/DD'),'2',2,'challenge','1',0,'0',6);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (100,'lyctg4620','인스타그램 팔로워 늘리기',to_date('23/05/08','RR/MM/DD'),'0',0,'accomplishment','1',0,'1',10);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (101,'lyctg4620','부모님께 안마의자 사드리기',to_date('23/05/08','RR/MM/DD'),'0',0,'relationships','1',0,'1',4);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (102,'lyctg4620','은사님 찾아뵙기',to_date('23/05/08','RR/MM/DD'),'0',0,'relationships','1',0,'1',6);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (103,'lyctg4620','나만의 드림카 장만하기',to_date('23/05/08','RR/MM/DD'),'0',0,'wealth','1',0,'1',10);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (104,'lyctg4620','디제잉 해보기',to_date('23/05/08','RR/MM/DD'),'0',0,'development','1',0,'1',3);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (105,'lyctg4620','중국어 배우기',to_date('23/05/08','RR/MM/DD'),'0',0,'study','1',0,'1',5);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (106,'lyctg4620','가족사진 찍기',to_date('23/05/08','RR/MM/DD'),'0',0,'relationships','0',0,'1',1);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (107,'lyctg4620','영어 회화 연습하기',to_date('23/05/08','RR/MM/DD'),'0',0,'training','1',0,'1',2);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (108,'lyctg4620','소중한 사람들에게 편지쓰기',to_date('23/05/08','RR/MM/DD'),'0',1,'relationships','1',0,'1',10);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (109,'thdthd123','재능 기부하기!',to_date('23/05/08','RR/MM/DD'),'0',1,'challenge','0',0,'1',1);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (110,'thdthd123','외국인 친구 만들기!',to_date('23/05/08','RR/MM/DD'),'0',4,'fun','0',0,'1',1);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (111,'chaechae','스위스 여행 꼭 가보기',to_date('23/05/08','RR/MM/DD'),'0',2,'travel','0',0,'1',1);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (112,'chaechae','퍼스트 클래스 타보기',to_date('23/05/08','RR/MM/DD'),'0',1,'wealth','0',0,'1',1);
Insert into C##GROUP7.BUCKET_REF (BUCKET_NO,USERID,TITLE,BUCKET_WRITEDATE,PROGRESS_STATUS,LIKE_COUNT,CATEGORY,ISGROUP,PROGRESS,ISVISIBLE,CAPACITY) values (113,'chaechae','꽃꽂이 도전!',to_date('23/05/08','RR/MM/DD'),'0',1,'travel','0',0,'0',1);
REM INSERTING into C##GROUP7.BUCKET_REPORT
SET DEFINE OFF;
Insert into C##GROUP7.BUCKET_REPORT (BUCKET_NO,TITLE,REPORT_NO,REPORT_TITLE,REPORT_CONTENT,REPORT_CATEGORY,REPORT_WRITEDATE,REPORT_USERID,REPORT_PROGRESS) values (61,'고양이 키우기',121,'전 고양이 싫어해요','강아지가 더 좋던데',3,to_date('23/05/08','RR/MM/DD'),'lyctg4620',0);
Insert into C##GROUP7.BUCKET_REPORT (BUCKET_NO,TITLE,REPORT_NO,REPORT_TITLE,REPORT_CONTENT,REPORT_CATEGORY,REPORT_WRITEDATE,REPORT_USERID,REPORT_PROGRESS) values (92,'김장해보기!!!',123,'김장 힘들어여','김장 못해!',3,to_date('23/05/08','RR/MM/DD'),'codnjs1003',2);
Insert into C##GROUP7.BUCKET_REPORT (BUCKET_NO,TITLE,REPORT_NO,REPORT_TITLE,REPORT_CONTENT,REPORT_CATEGORY,REPORT_WRITEDATE,REPORT_USERID,REPORT_PROGRESS) values (66,'올여름 맛집탐방 가실분!',122,'여름 휴가 없어요!!','여름휴가 없는데 이런거 올리면 자괴감 듭니다...',3,to_date('23/05/08','RR/MM/DD'),'test1234',0);
Insert into C##GROUP7.BUCKET_REPORT (BUCKET_NO,TITLE,REPORT_NO,REPORT_TITLE,REPORT_CONTENT,REPORT_CATEGORY,REPORT_WRITEDATE,REPORT_USERID,REPORT_PROGRESS) values (92,'김장해보기!!!',124,'김장 못해!','김장 어려워여',3,to_date('23/05/08','RR/MM/DD'),'codnjs1003',0);
Insert into C##GROUP7.BUCKET_REPORT (BUCKET_NO,TITLE,REPORT_NO,REPORT_TITLE,REPORT_CONTENT,REPORT_CATEGORY,REPORT_WRITEDATE,REPORT_USERID,REPORT_PROGRESS) values (112,'퍼스트 클래스 타보기',125,'광고','광고같아요',1,to_date('23/05/08','RR/MM/DD'),'lyctg4620',0);
REM INSERTING into C##GROUP7.COMMENT_BOARD
SET DEFINE OFF;
Insert into C##GROUP7.COMMENT_BOARD (C_NO,NO,USERID,WRITEDATE,IP) values (321,161,'cwcwcw123',to_date('23/05/08','RR/MM/DD'),'0:0:0:0:0:0:0:1');
Insert into C##GROUP7.COMMENT_BOARD (C_NO,NO,USERID,WRITEDATE,IP) values (322,161,'test1234',to_date('23/05/08','RR/MM/DD'),'0:0:0:0:0:0:0:1');
Insert into C##GROUP7.COMMENT_BOARD (C_NO,NO,USERID,WRITEDATE,IP) values (323,181,'codnjs1003',to_date('23/05/08','RR/MM/DD'),'0:0:0:0:0:0:0:1');
Insert into C##GROUP7.COMMENT_BOARD (C_NO,NO,USERID,WRITEDATE,IP) values (324,184,'tjdwns123',to_date('23/05/08','RR/MM/DD'),'0:0:0:0:0:0:0:1');
Insert into C##GROUP7.COMMENT_BOARD (C_NO,NO,USERID,WRITEDATE,IP) values (325,187,'tjdwns123',to_date('23/05/08','RR/MM/DD'),'0:0:0:0:0:0:0:1');
REM INSERTING into C##GROUP7.GROUP_BOARD_COMMENT
SET DEFINE OFF;
REM INSERTING into C##GROUP7.GROUP_BUCKET_BOARD
SET DEFINE OFF;
Insert into C##GROUP7.GROUP_BUCKET_BOARD (GROUP_BOARD_NO,GROUP_NO,USERID,GROUP_TITLE,GROUP_WRITEDATE,ISNOTICE) values (29,66,'cwcwcw123','맛집 탐방 시 유의사항!',to_date('23/05/08','RR/MM/DD'),'1');
Insert into C##GROUP7.GROUP_BUCKET_BOARD (GROUP_BOARD_NO,GROUP_NO,USERID,GROUP_TITLE,GROUP_WRITEDATE,ISNOTICE) values (31,74,'chaechae','5/10 20시 어떠세요',to_date('23/05/08','RR/MM/DD'),'1');
Insert into C##GROUP7.GROUP_BUCKET_BOARD (GROUP_BOARD_NO,GROUP_NO,USERID,GROUP_TITLE,GROUP_WRITEDATE,ISNOTICE) values (32,88,'tjdwns123','공지사항',to_date('23/05/08','RR/MM/DD'),'1');
Insert into C##GROUP7.GROUP_BUCKET_BOARD (GROUP_BOARD_NO,GROUP_NO,USERID,GROUP_TITLE,GROUP_WRITEDATE,ISNOTICE) values (30,74,'chaechae','가디언즈 오브 갤럭시 보러가요',to_date('23/05/08','RR/MM/DD'),'1');
Insert into C##GROUP7.GROUP_BUCKET_BOARD (GROUP_BOARD_NO,GROUP_NO,USERID,GROUP_TITLE,GROUP_WRITEDATE,ISNOTICE) values (33,88,'tjdwns123','책상 만들기~',to_date('23/05/08','RR/MM/DD'),'0');
REM INSERTING into C##GROUP7.GROUP_MEMBER_LIST
SET DEFINE OFF;
Insert into C##GROUP7.GROUP_MEMBER_LIST (USERID,GROUP_NO) values ('cwcwcw123',56);
Insert into C##GROUP7.GROUP_MEMBER_LIST (USERID,GROUP_NO) values ('lyctg4620',61);
Insert into C##GROUP7.GROUP_MEMBER_LIST (USERID,GROUP_NO) values ('lyctg4620',63);
Insert into C##GROUP7.GROUP_MEMBER_LIST (USERID,GROUP_NO) values ('lyctg4620',64);
Insert into C##GROUP7.GROUP_MEMBER_LIST (USERID,GROUP_NO) values ('cwcwcw123',65);
Insert into C##GROUP7.GROUP_MEMBER_LIST (USERID,GROUP_NO) values ('cwcwcw123',66);
Insert into C##GROUP7.GROUP_MEMBER_LIST (USERID,GROUP_NO) values ('lyctg4620',77);
Insert into C##GROUP7.GROUP_MEMBER_LIST (USERID,GROUP_NO) values ('lyctg4620',71);
Insert into C##GROUP7.GROUP_MEMBER_LIST (USERID,GROUP_NO) values ('lyctg4620',67);
Insert into C##GROUP7.GROUP_MEMBER_LIST (USERID,GROUP_NO) values ('test1234',70);
Insert into C##GROUP7.GROUP_MEMBER_LIST (USERID,GROUP_NO) values ('codnjs1003',73);
Insert into C##GROUP7.GROUP_MEMBER_LIST (USERID,GROUP_NO) values ('chaechae',74);
Insert into C##GROUP7.GROUP_MEMBER_LIST (USERID,GROUP_NO) values ('codnjs1003',78);
Insert into C##GROUP7.GROUP_MEMBER_LIST (USERID,GROUP_NO) values ('codnjs1003',79);
Insert into C##GROUP7.GROUP_MEMBER_LIST (USERID,GROUP_NO) values ('lyctg4620',80);
Insert into C##GROUP7.GROUP_MEMBER_LIST (USERID,GROUP_NO) values ('tjdwns123',88);
Insert into C##GROUP7.GROUP_MEMBER_LIST (USERID,GROUP_NO) values ('codnjs1003',89);
Insert into C##GROUP7.GROUP_MEMBER_LIST (USERID,GROUP_NO) values ('codnjs1003',90);
Insert into C##GROUP7.GROUP_MEMBER_LIST (USERID,GROUP_NO) values ('codnjs1003',80);
Insert into C##GROUP7.GROUP_MEMBER_LIST (USERID,GROUP_NO) values ('tjdwns123',80);
Insert into C##GROUP7.GROUP_MEMBER_LIST (USERID,GROUP_NO) values ('codnjs1003',95);
Insert into C##GROUP7.GROUP_MEMBER_LIST (USERID,GROUP_NO) values ('tjdwns123',71);
Insert into C##GROUP7.GROUP_MEMBER_LIST (USERID,GROUP_NO) values ('lyctg4620',100);
Insert into C##GROUP7.GROUP_MEMBER_LIST (USERID,GROUP_NO) values ('lyctg4620',101);
Insert into C##GROUP7.GROUP_MEMBER_LIST (USERID,GROUP_NO) values ('lyctg4620',102);
Insert into C##GROUP7.GROUP_MEMBER_LIST (USERID,GROUP_NO) values ('lyctg4620',103);
Insert into C##GROUP7.GROUP_MEMBER_LIST (USERID,GROUP_NO) values ('lyctg4620',104);
Insert into C##GROUP7.GROUP_MEMBER_LIST (USERID,GROUP_NO) values ('lyctg4620',105);
Insert into C##GROUP7.GROUP_MEMBER_LIST (USERID,GROUP_NO) values ('lyctg4620',107);
Insert into C##GROUP7.GROUP_MEMBER_LIST (USERID,GROUP_NO) values ('lyctg4620',108);
REM INSERTING into C##GROUP7.GROUP_QUEUE
SET DEFINE OFF;
Insert into C##GROUP7.GROUP_QUEUE (GROUP_NO,USERID) values (66,'chaechae');
Insert into C##GROUP7.GROUP_QUEUE (GROUP_NO,USERID) values (56,'chaechae');
Insert into C##GROUP7.GROUP_QUEUE (GROUP_NO,USERID) values (74,'test1234');
Insert into C##GROUP7.GROUP_QUEUE (GROUP_NO,USERID) values (73,'chaechae');
Insert into C##GROUP7.GROUP_QUEUE (GROUP_NO,USERID) values (78,'tjdwns123');
Insert into C##GROUP7.GROUP_QUEUE (GROUP_NO,USERID) values (88,'codnjs1003');
Insert into C##GROUP7.GROUP_QUEUE (GROUP_NO,USERID) values (89,'chaechae');
REM INSERTING into C##GROUP7.IMAGEPATH
SET DEFINE OFF;
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (62,'naver(15).png');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (53,'blackpink_consert(1).jpeg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (59,'월요일좋아(2)(2).jpeg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (100,'instagram.png');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (56,'1.jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (60,'puppy.jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (58,'월요일좋아(2)(1).jpeg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (61,'03(3).jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (63,'jeju_map(7).jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (64,'bowling.jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (65,'독서(1).jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (66,'맛집탐방(1).jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (67,'soccer.jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (68,'pexels-rafael-guimar?es-1060791 (1).jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (69,'pexels-aline-viana-prado-2465877.jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (70,'pexels-adi-perets-5156296.jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (71,'tennis.jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (73,'디저트카페(1).jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (74,'guardians_movie_poster.jpeg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (76,'pexels-sascha-d?ser-187329.jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (77,'fitness.jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (78,'swim(1).jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (79,'뜨개질 가방(1).jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (80,'omakase.jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (87,'무지개염색(1).jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (88,'pexels-alex-qian-2343473.jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (89,'연극(1).jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (90,'비즈팔찌(1).jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (91,'pexels-stephanie-ho-1214212.jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (92,'pexels-roman-odintsov-5338145.jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (96,'불멍.jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (95,'드로잉(1).jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (99,'son.jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (101,'messageChair.jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (102,'teacher.jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (103,'car.jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (104,'DJ.jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (105,'chinese.png');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (106,'familyphoto.jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (107,'conversation.jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (108,'letter.png');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (109,'pexels-gimmeges-37719.jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (110,'pexels-rachel-claire-4846093.jpg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (111,'switzerland.jpeg');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (112,'firstclass.png');
Insert into C##GROUP7.IMAGEPATH (BUCKET_NO,FILENAME) values (113,'flowerflower.jpeg');
REM INSERTING into C##GROUP7.PROFILE
SET DEFINE OFF;
Insert into C##GROUP7.PROFILE (USERID,STATUS_MESSAGE,FILENAME,PROFILE_VISIBLE) values ('chriso1234',null,null,'1');
Insert into C##GROUP7.PROFILE (USERID,STATUS_MESSAGE,FILENAME,PROFILE_VISIBLE) values ('cwcwcw123',null,null,'1');
Insert into C##GROUP7.PROFILE (USERID,STATUS_MESSAGE,FILENAME,PROFILE_VISIBLE) values ('lyctg4620','안녕하세요~!','profile.png','1');
Insert into C##GROUP7.PROFILE (USERID,STATUS_MESSAGE,FILENAME,PROFILE_VISIBLE) values ('chaechae','게임, 영화, 노래 이것저것 다 좋아함',null,'1');
Insert into C##GROUP7.PROFILE (USERID,STATUS_MESSAGE,FILENAME,PROFILE_VISIBLE) values ('test1234',null,'정국.jpeg','1');
Insert into C##GROUP7.PROFILE (USERID,STATUS_MESSAGE,FILENAME,PROFILE_VISIBLE) values ('chriso12345','상태 메세지','1f6a80414e540da3b24e7b87d7788a7d-sticker.png','1');
Insert into C##GROUP7.PROFILE (USERID,STATUS_MESSAGE,FILENAME,PROFILE_VISIBLE) values ('admin1234',null,'월요일좋아(2)22.jpeg','1');
Insert into C##GROUP7.PROFILE (USERID,STATUS_MESSAGE,FILENAME,PROFILE_VISIBLE) values ('codnjs1003',null,'cs(1).png','1');
Insert into C##GROUP7.PROFILE (USERID,STATUS_MESSAGE,FILENAME,PROFILE_VISIBLE) values ('codnjs10033',null,null,'1');
Insert into C##GROUP7.PROFILE (USERID,STATUS_MESSAGE,FILENAME,PROFILE_VISIBLE) values ('tjdwns123',null,null,'1');
Insert into C##GROUP7.PROFILE (USERID,STATUS_MESSAGE,FILENAME,PROFILE_VISIBLE) values ('thdthd123',null,null,'1');
REM INSERTING into C##GROUP7.USERTABLE
SET DEFINE OFF;
Insert into C##GROUP7.USERTABLE (USERID,USERPWD,USERNAME,TEL,EMAIL,USERNICK,REGISTERDATE,PERMISSION,NO) values ('codnjs1003','codnjs1003','김채원','01011112222','codnjs1003@naver.com','뺘냐나',to_date('23/05/08','RR/MM/DD'),'0',41);
Insert into C##GROUP7.USERTABLE (USERID,USERPWD,USERNAME,TEL,EMAIL,USERNICK,REGISTERDATE,PERMISSION,NO) values ('cwcwcw123','12345678','김김김','01012345678','cwcwcw@ccc.com','꺠굴이',to_date('23/05/06','RR/MM/DD'),'0',25);
Insert into C##GROUP7.USERTABLE (USERID,USERPWD,USERNAME,TEL,EMAIL,USERNICK,REGISTERDATE,PERMISSION,NO) values ('lyctg4620','12345678','이예찬','010-7634-8992','lyctg1234@naver.com','예찬',to_date('23/05/06','RR/MM/DD'),'0',24);
Insert into C##GROUP7.USERTABLE (USERID,USERPWD,USERNAME,TEL,EMAIL,USERNICK,REGISTERDATE,PERMISSION,NO) values ('chriso1234','Chriso1234','길홍배','01012345678','chriso@gmail.com','chriso',to_date('23/05/06','RR/MM/DD'),'0',21);
Insert into C##GROUP7.USERTABLE (USERID,USERPWD,USERNAME,TEL,EMAIL,USERNICK,REGISTERDATE,PERMISSION,NO) values ('chaechae','12341234','김채린','01011112222','xxchrn@gmail.com','chaerin',to_date('23/05/06','RR/MM/DD'),'0',23);
Insert into C##GROUP7.USERTABLE (USERID,USERPWD,USERNAME,TEL,EMAIL,USERNICK,REGISTERDATE,PERMISSION,NO) values ('test1234','12345678','세종대왕','01011112222','gprhf123@gmail.com','세종대왕',to_date('23/05/06','RR/MM/DD'),'0',22);
Insert into C##GROUP7.USERTABLE (USERID,USERPWD,USERNAME,TEL,EMAIL,USERNICK,REGISTERDATE,PERMISSION,NO) values ('chriso12345','Chriso1234','길홍배','01012345678','chriso@gmail.com','chrisooo',to_date('23/05/06','RR/MM/DD'),'0',23);
Insert into C##GROUP7.USERTABLE (USERID,USERPWD,USERNAME,TEL,EMAIL,USERNICK,REGISTERDATE,PERMISSION,NO) values ('tjdwns123','12345678','김동동','01011112222','abcdef@nate.com','김동동동',to_date('23/05/08','RR/MM/DD'),'0',42);
Insert into C##GROUP7.USERTABLE (USERID,USERPWD,USERNAME,TEL,EMAIL,USERNICK,REGISTERDATE,PERMISSION,NO) values ('thdthd123','12345678','송송이','01011112222','qwerrr@nate.com','송송이',to_date('23/05/08','RR/MM/DD'),'0',43);
Insert into C##GROUP7.USERTABLE (USERID,USERPWD,USERNAME,TEL,EMAIL,USERNICK,REGISTERDATE,PERMISSION,NO) values ('codnjs10033','12345678','김채원','01022223333','kcw2336@naver.com','뀨를',to_date('23/05/08','RR/MM/DD'),'0',44);
Insert into C##GROUP7.USERTABLE (USERID,USERPWD,USERNAME,TEL,EMAIL,USERNICK,REGISTERDATE,PERMISSION,NO) values ('admin1234','12345678','관리자','333','test@test.com','관리자',to_date('23/05/05','RR/MM/DD'),'9',1);
--------------------------------------------------------
--  DDL for Index PK_COMMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GROUP7"."PK_COMMENT" ON "C##GROUP7"."BUCKET_COMMENT" ("COMMENT_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_GROUP_BUCKET_BOARD
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GROUP7"."PK_GROUP_BUCKET_BOARD" ON "C##GROUP7"."GROUP_BUCKET_BOARD" ("GROUP_BOARD_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_LIKE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GROUP7"."PK_LIKE" ON "C##GROUP7"."BUCKET_LIKE" ("LIKE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_PROFILE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GROUP7"."PK_PROFILE" ON "C##GROUP7"."PROFILE" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_GROUP_COMMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GROUP7"."PK_GROUP_COMMENT" ON "C##GROUP7"."GROUP_BOARD_COMMENT" ("GROUP_COMMENT_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_BUCKET_REF
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GROUP7"."PK_BUCKET_REF" ON "C##GROUP7"."BUCKET_REF" ("BUCKET_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_USER
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GROUP7"."PK_USER" ON "C##GROUP7"."USERTABLE" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table GROUP_QUEUE
--------------------------------------------------------

  ALTER TABLE "C##GROUP7"."GROUP_QUEUE" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."GROUP_QUEUE" MODIFY ("GROUP_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GROUP_BOARD_COMMENT
--------------------------------------------------------

  ALTER TABLE "C##GROUP7"."GROUP_BOARD_COMMENT" ADD CONSTRAINT "PK_GROUP_COMMENT" PRIMARY KEY ("GROUP_COMMENT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "C##GROUP7"."GROUP_BOARD_COMMENT" MODIFY ("GROUP_COMMENT_WRITEDATE" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."GROUP_BOARD_COMMENT" MODIFY ("GROUP_COMMENT_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."GROUP_BOARD_COMMENT" MODIFY ("GROUP_BOARD_NO" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."GROUP_BOARD_COMMENT" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."GROUP_BOARD_COMMENT" MODIFY ("GROUP_NO" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."GROUP_BOARD_COMMENT" MODIFY ("GROUP_COMMENT_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BUCKET_COMMENT
--------------------------------------------------------

  ALTER TABLE "C##GROUP7"."BUCKET_COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY ("COMMENT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "C##GROUP7"."BUCKET_COMMENT" MODIFY ("COMMENT_WRITEDATE" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."BUCKET_COMMENT" MODIFY ("COMMENT_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."BUCKET_COMMENT" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."BUCKET_COMMENT" MODIFY ("BUCKET_NO" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."BUCKET_COMMENT" MODIFY ("COMMENT_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "C##GROUP7"."BOARD" MODIFY ("NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IMAGEPATH
--------------------------------------------------------

  ALTER TABLE "C##GROUP7"."IMAGEPATH" MODIFY ("FILENAME" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."IMAGEPATH" MODIFY ("BUCKET_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BUCKET_LIKE
--------------------------------------------------------

  ALTER TABLE "C##GROUP7"."BUCKET_LIKE" ADD CONSTRAINT "PK_LIKE" PRIMARY KEY ("LIKE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "C##GROUP7"."BUCKET_LIKE" MODIFY ("LIKE_NO" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."BUCKET_LIKE" MODIFY ("BUCKET_NO" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."BUCKET_LIKE" MODIFY ("USERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GROUP_BUCKET_BOARD
--------------------------------------------------------

  ALTER TABLE "C##GROUP7"."GROUP_BUCKET_BOARD" ADD CONSTRAINT "PK_GROUP_BUCKET_BOARD" PRIMARY KEY ("GROUP_BOARD_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "C##GROUP7"."GROUP_BUCKET_BOARD" MODIFY ("ISNOTICE" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."GROUP_BUCKET_BOARD" MODIFY ("GROUP_WRITEDATE" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."GROUP_BUCKET_BOARD" MODIFY ("GROUP_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."GROUP_BUCKET_BOARD" MODIFY ("GROUP_TITLE" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."GROUP_BUCKET_BOARD" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."GROUP_BUCKET_BOARD" MODIFY ("GROUP_NO" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."GROUP_BUCKET_BOARD" MODIFY ("GROUP_BOARD_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GROUP_MEMBER_LIST
--------------------------------------------------------

  ALTER TABLE "C##GROUP7"."GROUP_MEMBER_LIST" MODIFY ("GROUP_NO" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."GROUP_MEMBER_LIST" MODIFY ("USERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BUCKET_REPORT
--------------------------------------------------------

  ALTER TABLE "C##GROUP7"."BUCKET_REPORT" MODIFY ("REPORT_USERID" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."BUCKET_REPORT" MODIFY ("REPORT_CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."BUCKET_REPORT" MODIFY ("REPORT_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."BUCKET_REPORT" MODIFY ("REPORT_TITLE" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."BUCKET_REPORT" MODIFY ("REPORT_NO" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."BUCKET_REPORT" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."BUCKET_REPORT" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."BUCKET_REPORT" MODIFY ("BUCKET_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERTABLE
--------------------------------------------------------

  ALTER TABLE "C##GROUP7"."USERTABLE" ADD CONSTRAINT "PK_USER" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "C##GROUP7"."USERTABLE" MODIFY ("PERMISSION" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."USERTABLE" MODIFY ("REGISTERDATE" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."USERTABLE" MODIFY ("USERNICK" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."USERTABLE" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."USERTABLE" MODIFY ("TEL" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."USERTABLE" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."USERTABLE" MODIFY ("USERPWD" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."USERTABLE" MODIFY ("USERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROFILE
--------------------------------------------------------

  ALTER TABLE "C##GROUP7"."PROFILE" ADD CONSTRAINT "PK_PROFILE" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "C##GROUP7"."PROFILE" MODIFY ("PROFILE_VISIBLE" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."PROFILE" MODIFY ("USERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BUCKET_REF
--------------------------------------------------------

  ALTER TABLE "C##GROUP7"."BUCKET_REF" MODIFY ("CAPACITY" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."BUCKET_REF" ADD CONSTRAINT "PK_BUCKET_REF" PRIMARY KEY ("BUCKET_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "C##GROUP7"."BUCKET_REF" MODIFY ("ISGROUP" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."BUCKET_REF" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."BUCKET_REF" MODIFY ("LIKE_COUNT" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."BUCKET_REF" MODIFY ("PROGRESS_STATUS" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."BUCKET_REF" MODIFY ("BUCKET_WRITEDATE" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."BUCKET_REF" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."BUCKET_REF" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."BUCKET_REF" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."BUCKET_REF" MODIFY ("BUCKET_NO" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."BUCKET_REF" MODIFY ("ISVISIBLE" NOT NULL ENABLE);
  ALTER TABLE "C##GROUP7"."BUCKET_REF" MODIFY ("PROGRESS" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "C##GROUP7"."BOARD" ADD CONSTRAINT "FK_BOARD_USERID_CASCADE" FOREIGN KEY ("USERID")
	  REFERENCES "C##GROUP7"."USERTABLE" ("USERID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BUCKET_COMMENT
--------------------------------------------------------

  ALTER TABLE "C##GROUP7"."BUCKET_COMMENT" ADD CONSTRAINT "FK_COMMENT_NO_CASCADE" FOREIGN KEY ("BUCKET_NO")
	  REFERENCES "C##GROUP7"."BUCKET_REF" ("BUCKET_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##GROUP7"."BUCKET_COMMENT" ADD CONSTRAINT "FK_COMMENT_USERID_CASCADE" FOREIGN KEY ("USERID")
	  REFERENCES "C##GROUP7"."USERTABLE" ("USERID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BUCKET_LIKE
--------------------------------------------------------

  ALTER TABLE "C##GROUP7"."BUCKET_LIKE" ADD CONSTRAINT "FK_BUCKET_LIST_NO_CASCADE" FOREIGN KEY ("BUCKET_NO")
	  REFERENCES "C##GROUP7"."BUCKET_REF" ("BUCKET_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##GROUP7"."BUCKET_LIKE" ADD CONSTRAINT "FK_BUCKET_LIST_USERID_CASCADE" FOREIGN KEY ("USERID")
	  REFERENCES "C##GROUP7"."USERTABLE" ("USERID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BUCKET_REF
--------------------------------------------------------

  ALTER TABLE "C##GROUP7"."BUCKET_REF" ADD CONSTRAINT "FK_BUCKET_REF_CASCADE" FOREIGN KEY ("USERID")
	  REFERENCES "C##GROUP7"."USERTABLE" ("USERID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BUCKET_REPORT
--------------------------------------------------------

  ALTER TABLE "C##GROUP7"."BUCKET_REPORT" ADD CONSTRAINT "FK_BUCKET_REPORT_NO_CASCADE" FOREIGN KEY ("BUCKET_NO")
	  REFERENCES "C##GROUP7"."BUCKET_REF" ("BUCKET_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##GROUP7"."BUCKET_REPORT" ADD CONSTRAINT "FK_BUCKET_REPORT_USER_CASCADE" FOREIGN KEY ("REPORT_USERID")
	  REFERENCES "C##GROUP7"."USERTABLE" ("USERID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMENT_BOARD
--------------------------------------------------------

  ALTER TABLE "C##GROUP7"."COMMENT_BOARD" ADD CONSTRAINT "FK_C_BOARD_USERID_CASCADE" FOREIGN KEY ("USERID")
	  REFERENCES "C##GROUP7"."USERTABLE" ("USERID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GROUP_BOARD_COMMENT
--------------------------------------------------------

  ALTER TABLE "C##GROUP7"."GROUP_BOARD_COMMENT" ADD CONSTRAINT "FK_G_COMMENT_BOARD_NO_CASCADE" FOREIGN KEY ("GROUP_BOARD_NO")
	  REFERENCES "C##GROUP7"."GROUP_BUCKET_BOARD" ("GROUP_BOARD_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##GROUP7"."GROUP_BOARD_COMMENT" ADD CONSTRAINT "FK_G_COMMENT_GROUP_NO_CASCADE" FOREIGN KEY ("GROUP_NO")
	  REFERENCES "C##GROUP7"."BUCKET_REF" ("BUCKET_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##GROUP7"."GROUP_BOARD_COMMENT" ADD CONSTRAINT "FK_G_COMMENT_USERID_CASCADE" FOREIGN KEY ("USERID")
	  REFERENCES "C##GROUP7"."USERTABLE" ("USERID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GROUP_BUCKET_BOARD
--------------------------------------------------------

  ALTER TABLE "C##GROUP7"."GROUP_BUCKET_BOARD" ADD CONSTRAINT "FK_GROUP_BOARD_NO_CASCADE" FOREIGN KEY ("GROUP_NO")
	  REFERENCES "C##GROUP7"."BUCKET_REF" ("BUCKET_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##GROUP7"."GROUP_BUCKET_BOARD" ADD CONSTRAINT "FK_GROUP_BOARD_USERID_CASCADE" FOREIGN KEY ("USERID")
	  REFERENCES "C##GROUP7"."USERTABLE" ("USERID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GROUP_MEMBER_LIST
--------------------------------------------------------

  ALTER TABLE "C##GROUP7"."GROUP_MEMBER_LIST" ADD CONSTRAINT "FK_GROUP_MEMBER_NO_CASCADE" FOREIGN KEY ("GROUP_NO")
	  REFERENCES "C##GROUP7"."BUCKET_REF" ("BUCKET_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##GROUP7"."GROUP_MEMBER_LIST" ADD CONSTRAINT "FK_GROUP_MEMBER_USERID_CASCADE" FOREIGN KEY ("USERID")
	  REFERENCES "C##GROUP7"."USERTABLE" ("USERID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GROUP_QUEUE
--------------------------------------------------------

  ALTER TABLE "C##GROUP7"."GROUP_QUEUE" ADD CONSTRAINT "FK_GROUP_QUEUE_NO_CASCADE" FOREIGN KEY ("GROUP_NO")
	  REFERENCES "C##GROUP7"."BUCKET_REF" ("BUCKET_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##GROUP7"."GROUP_QUEUE" ADD CONSTRAINT "FK_GROUP_QUEUE_USERID_CASCADE" FOREIGN KEY ("USERID")
	  REFERENCES "C##GROUP7"."USERTABLE" ("USERID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table IMAGEPATH
--------------------------------------------------------

  ALTER TABLE "C##GROUP7"."IMAGEPATH" ADD CONSTRAINT "FK_IMAGEPATH_NO_CASCADE" FOREIGN KEY ("BUCKET_NO")
	  REFERENCES "C##GROUP7"."BUCKET_REF" ("BUCKET_NO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROFILE
--------------------------------------------------------

  ALTER TABLE "C##GROUP7"."PROFILE" ADD CONSTRAINT "FK_PROFILE_USERID_CASCADE" FOREIGN KEY ("USERID")
	  REFERENCES "C##GROUP7"."USERTABLE" ("USERID") ON DELETE CASCADE ENABLE;
